version: "2"
services:
  simple_habit:
    container_name: simple-habit
    restart: always
    build: .
    ports:
      - "22000:22000"
    links:
      - mongo
  mongo:
    container_name: simple-habit-mongo
    image: mongo
    ports:
      - "27018:27017"